FROM bellsoft/liberica-openjdk-alpine:19

USER 1000

ENTRYPOINT ["/center.sciprog.tasks_bot.launcher/bin/center.sciprog.tasks_bot.launcher", "/config.json"]

ADD ./build/distributions/center.sciprog.tasks_bot.launcher.tar /
